version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      ignore:
        - dependency-name: "net.portswigger.burp.extensions:montoya-api"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
